version: 2.1
jobs:
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: ssh circleci@157.245.107.135 "./deploy_project.sh"
  build:
    docker:
      - image: circleci/node:12.14.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
workflows:
  production_deployment:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master